version: "3.0"

services:
  sms-gateway:
    image: "webdevops/php-nginx:8.1"
    container_name: sms-gateway
    working_dir: /app
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
    volumes:
      - .:/app
      - './docker/supervisor/laravel-worker.conf:/opt/docker/etc/supervisor.d/laravel-worker.conf'
    ports:
      - 8000:80
    depends_on:
      - db
      
  db:
    image: mysql
    container_name: db 
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=sms_gateway
      - MYSQL_USER=mohammad
      - MYSQL_PASSWORD=12345678
    volumes:
      - ./database-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq 
    environment:
      - RABBITMQ_DEFAULT_USER=mohammad
      - RABBITMQ_DEFAULT_PASS=12345678
    ports:
      - 5672:5672

  pma:
    image: phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_USER=mohammad
      - PMA_PASSWORD=12345678
      - PMA_HOSTS=db
      - PMA_PORTS=3306
      - MYSQL_USER=mohammad
      - MYSQL_PASSWORD=12345678

    depends_on:
      - db
